name: Build and Publish Artifact

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'

    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: gui.py
        mode: onefile
        mingw64: true
        enable-plugins: tk-inter
        windows-icon-from-ico: schneeflocke.ico
        include-data-files: schneeflocke.ico=schneeflocke.ico

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: build/gui.dist/gui.exe
        include-hidden-files: true