name: Build and Publish Artifact

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: tobix/pywine:3.12

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install dependencies
      run: |
        wine pip install -r /app/requirements.txt 

    - name: Build Artifact
      run: |
        wine python -m PyInstaller --add-data /app/schneeflocke.ico:. --icon /app/schneeflocke.ico /app/gui.py

    - name: Upload Built Artifact
      uses: actions/upload-artifact@v3
      with:
        name: calculator
        path: dist
