name: Build and Publish Artifact

on:
  push:
    branches:
      - main
      - feature/replace-numpy
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: gui.py
        output-file: calculator.exe
        mode: onefile
        enable-plugins: tk-inter
        windows-icon-from-ico: schneeflocke.ico
        include-data-files: schneeflocke.ico=schneeflocke.ico

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator
        path: build/calculator.exe
        include-hidden-files: true

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/calculator.exe